<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <IsPackable>false</IsPackable>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DealerManagementSystem.Application\DealerManagementSystem.Application.csproj" />
    <ProjectReference Include="..\DealerManagementSystem.Infrastructure\DealerManagementSystem.Infrastructure.csproj" />
    <ProjectReference Include="..\DealerManagementSystem.Domain\DealerManagementSystem.Domain.csproj" />
    <ProjectReference Include="..\DealerManagementSystem.API\DealerManagementSystem.API.csproj" />
  </ItemGroup>

</Project>